## Name: Mahboob Ali
## Sec: C
## Roll Num: 119
## Lab 4

## Sets
## Exercise 1

In [34]:
A= {1,3,5,6,11};
B= { 2,7,8,11,4};
print(" Union ",A|B )
print(" Intersection ",A&B)
print(" Difference : A-B", A-B)
print(" Differnce B-A:",  B-A)
print(" Symmetric Difference  A^b:",  A^B)
print(2 in B)

print( A)


 Union  {1, 2, 3, 4, 5, 6, 7, 8, 11}
 Intersection  {11}
 Difference : A-B {1, 3, 5, 6}
 Differnce B-A: {8, 2, 4, 7}
 Symmetric Difference  A^b: {1, 2, 3, 4, 5, 6, 7, 8}
True
{1, 3, 5, 6, 11}


## Sets
## Exercise 2

In [28]:
mylist= [2,4,6,8,2,8,9,2,11,13,2,15]
mylist= list(set(mylist))

print (mylist)

[2, 4, 6, 8, 9, 11, 13, 15]


## NUMPY
## Exercise 3

In [7]:
import numpy as np

arr1= np.arange( 1,11)
print("Array:",arr1)
arr1= arr1[arr1>5]
print("Numbers greater than 5",arr1)





Array: [ 1  2  3  4  5  6  7  8  9 10]
Numbers greater than 5 [ 6  7  8  9 10]


## Exercise 4

In [8]:

arr1=np.array([[2, 4, 6, 8, 9, 12],
                 [2, 5, 7, 8, 11, 24]])



print("Sum of matrix ",np.sum(arr1))
print("mean of matrix ",np.mean(arr1))
print("max of matrix ",np.max(arr1))
print("min of matrix ",np.min(arr1))

Sum of matrix  98
mean of matrix  8.166666666666666
max of matrix  24
min of matrix  2


## Exercise 5

In [9]:
arr= np.linspace(0,5,10)
print("Numbers",arr)

print("multiplied by 3",
      arr*3)

Numbers [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
multiplied by 3 [ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


## Task 1

In [10]:
A= {2,4,6,8,9,11}
B= {4,6,7,9,11,34,56}
print(" Union ",A|B )
print(" Intersection ",A&B)
print(" Difference : A-B", A-B)
print(" Differnce B-A:",  B-A)
print(" Symmetric Difference  A^b:",  A^B)
print(2 in B)




 Union  {2, 34, 4, 6, 7, 8, 9, 11, 56}
 Intersection  {9, 11, 4, 6}
 Difference : A-B {8, 2}
 Differnce B-A: {56, 34, 7}
 Symmetric Difference  A^b: {34, 2, 7, 8, 56}
False


## Task 2

In [11]:

my_list = [1, 2, 3, 2, 4, 1, 5, 3, 6]


unique_list = list(set(my_list))

print("Original list:", my_list)
print("List after removing duplicates:", unique_list)


Original list: [1, 2, 3, 2, 4, 1, 5, 3, 6]
List after removing duplicates: [1, 2, 3, 4, 5, 6]


## Task 3

In [14]:
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

# Element-wise arithmetic operations
print("Add 5:", arr + 5)
print("Subtract 5:", arr - 5)
print("Multiply by 2:", arr * 2)
print("Divide by 10:", arr / 10)
print("Square:", arr ** 2)

Original array: [10 20 30 40 50]
Add 5: [15 25 35 45 55]
Subtract 5: [ 5 15 25 35 45]
Multiply by 2: [ 20  40  60  80 100]
Divide by 10: [1. 2. 3. 4. 5.]
Square: [ 100  400  900 1600 2500]


## Task 4

In [45]:

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))


Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Standard Deviation: 14.142135623730951


## Task 5

In [56]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
second_row = arr[1, :]
second_column = arr[:, 1]

print("\nSecond Row:", second_row)
print("Second Column:", second_column)



Second Row: [4 5 6]
Second Column: [2 5 8]


## Task 6

In [17]:
arr = np.arange(10, 50, 5)

print("Array:", arr)


Array: [10 15 20 25 30 35 40 45]


## Task 7

In [59]:
arr = np.linspace(0, 10, 15)

print("1D Array:\n", arr)


matrix = arr.reshape(3, 5)

print("Reshaped 3x5 Matrix:\n", matrix)

1D Array:
 [ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
Reshaped 3x5 Matrix:
 [[ 0.          0.71428571  1.42857143  2.14285714  2.85714286]
 [ 3.57142857  4.28571429  5.          5.71428571  6.42857143]
 [ 7.14285714  7.85714286  8.57142857  9.28571429 10.        ]]


## Task 8

In [61]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
even= arr[arr%2==0]
print("even", even)

even [2 4 6 8]


## Task 9

In [62]:

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

v_merge = np.vstack((arr1, arr2))

h_merge = np.hstack((arr1, arr2))

print("Merged Vertically:\n", v_merge)
print("Merged Horizontally:\n", h_merge)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Merged Vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Merged Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]


## Task 10

In [64]:
identity_matrix = np.identity(5)

print("5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
